image: kroniak/ssh-client
pipelines:
  branches:
    master:
      - step:
          name: deploy to staging
          image: kroniak/ssh-client
          deployment: staging
          script:
            - |
                ssh mradmin@devops.mrmilu.com \
                -o "StrictHostKeyChecking no" \
                -o "UserKnownHostsFile=/dev/null" \
                'cd /data/provision/utopicus.landings.provision; git pull'
            - |
                ssh mradmin@devops.mrmilu.com \
                -o "StrictHostKeyChecking no" \
                -o "UserKnownHostsFile=/dev/null" \
                'cd /data/provision/utopicus.landings.provision; ansible-playbook -i inventory/staging site.yml -c paramiko'